require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  # DisabledByDefault: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/puma.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/environments/production.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  ExcludedMethods: ['context']
  Exclude:
    - 'config/environments/development.rb'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 200

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/admins/base_controller.rb'
    - 'app/controllers/users/base_controller.rb'
    - 'test/controllers/concerns/breadcrumbs_test.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'

Minitest/MultipleAssertions:
  Max: 4

